name: quotes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  dartz: ^0.10.1



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
     - assets/images/

  fonts:
   - family: Tajawal
     fonts:
         - asset: assets/fonts/Tajawal-Regular.ttf
         - asset: assets/fonts/Tajawal-Bold.ttf
         - asset: assets/fonts/Tajawal-ExtraBold.ttf
         - asset: assets/fonts/Tajawal-Light.ttf
         - asset: assets/fonts/Tajawal-ExtraLight.ttf
         - asset: assets/fonts/Tajawal-Medium.ttf
